# Change these first
owner: SukiCZ # Your GitHub organization or username, where this repository lives
repo: UpptimeRobot # The name of this repository

sites:
  - name: MH Clinic
    url: https://mhclinic.cz
  - name: Chameleon
    url: https://chameleon.suki.wtf
  - name: Barré
    url: https://barre.suki.wtf/api/status/

assignees: # Users to assign downtime issues (optional)
  - SukiCZ

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /UpptimeRobot
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UpptimeRobot
  introTitle: "**UpptimeRobot** powered by Upptime."
  introMessage: UptimeRobot powered by Upptime. [**Get your own for free**](https://github.com/upptime/upptime)
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
